"""initial schema

Revision ID: 900210dd58ca
Revises: 
Create Date: 2026-09-09 09:35:40.567352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900210dd58ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('net_capital_inflow', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'mode', name='uq_snapshot_date_mode')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('pair', sa.String(length=16), nullable=True),
    sa.Column('asset', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('amount_thb', sa.Float(), nullable=False),
    sa.Column('fee_thb', sa.Float(), nullable=False),
    sa.Column('price_thb', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_plans',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('entry_time', sa.String(length=64), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('entry_score', sa.Integer(), nullable=False),
    sa.Column('entry_reason', sa.Text(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('effective_stop', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=False),
    sa.Column('take_profit_2', sa.Float(), nullable=False),
    sa.Column('highest_price', sa.Float(), nullable=False),
    sa.Column('trailing_enabled', sa.Integer(), nullable=False),
    sa.Column('trailing_activation_percent', sa.Float(), nullable=False),
    sa.Column('trailing_distance_percent', sa.Float(), nullable=False),
    sa.Column('current_action', sa.String(length=32), nullable=False),
    sa.Column('action_reason', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('mode')
    )
    op.create_table('positions',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('mode', 'asset')
    )
    op.create_table('prices',
    sa.Column('pair', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('pair')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('pair', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('settings')
    op.drop_table('prices')
    op.drop_table('positions')
    op.drop_table('position_plans')
    op.drop_table('notifications')
    op.drop_table('ledger')
    op.drop_table('journal')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
